// Copyright (c) 2026 VAIS contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using FluentAssertions;
using Vais.Agents.Control.Manifests;
using Xunit;

namespace Vais.Agents.Core.Tests;

/// <summary>
/// MS-3-B guard — per-kind reference docs under <c>contracts/reference/</c> are rendered
/// from the generated JSON Schema (the correct wire shape) plus the checked-in example,
/// so the field tables can't drift from the records/codec. Run with
/// <c>VAIS_UPDATE_REFERENCE=1</c> to regenerate. Descriptions (from XML doc comments) are a
/// follow-up; this slice covers field/type/required + the example.
/// </summary>
public sealed class ManifestReferenceDocTests
{
    public static IEnumerable<object[]> Kinds() =>
    [
        ["Agent", typeof(AgentManifest)],
        ["AgentGraph", typeof(AgentGraphManifest)],
        ["McpServer", typeof(McpServerManifest)],
        ["LlmGatewayConfig", typeof(LlmGatewayConfigManifest)],
        ["McpGatewayConfig", typeof(McpGatewayConfigManifest)],
        ["ContainerPlugin", typeof(ContainerPluginManifest)],
        ["EvalSuite", typeof(EvalSuiteManifest)],
    ];

    [Theory]
    [MemberData(nameof(Kinds))]
    public void ReferenceDoc_IsCheckedIn_AndUpToDate(string kind, Type recordType)
    {
        var schema = ManifestJsonSchemaGenerator.GenerateEnvelopeSchema(recordType, kind, XmlDocSummaries.ForAbstractions());
        var doc = Render(kind, schema, ReadExample(kind));
        var path = DocPath(kind);

        if (Environment.GetEnvironmentVariable("VAIS_UPDATE_REFERENCE") == "1")
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, doc);
            return;
        }

        File.Exists(path).Should().BeTrue(
            $"the {kind} reference doc must be checked in at contracts/reference/ (run with VAIS_UPDATE_REFERENCE=1 to regenerate)");
        Normalize(File.ReadAllText(path)).Should().Be(Normalize(doc),
            because: $"the checked-in {kind} reference doc must match the generator (run with VAIS_UPDATE_REFERENCE=1 to regenerate)");
    }

    // ── markdown rendering (from the JSON Schema) ───────────────────────────────

    private static string Render(string kind, string schemaJson, string exampleYaml)
    {
        var sb = new StringBuilder();
        sb.Append("<!-- Generated by ManifestReferenceDocTests (VAIS_UPDATE_REFERENCE=1). Do not edit by hand. -->\n\n");
        sb.Append($"# `{kind}` manifest\n\n");
        sb.Append($"Reference for `kind: {kind}` (apiVersion `vais.agents/v1`). ");
        sb.Append($"Authoring schema: [`{kind}.schema.json`](../schemas/{kind}.schema.json).\n\n");

        sb.Append("## Example\n\n```yaml\n");
        sb.Append(exampleYaml.TrimEnd('\n'));
        sb.Append("\n```\n\n");

        sb.Append("## Fields\n\n| Path | Type | Required | Description |\n|------|------|----------|-------------|\n");
        using var doc = JsonDocument.Parse(schemaJson);
        foreach (var row in WalkObject(doc.RootElement, ""))
            sb.Append($"| `{row.Path}` | {row.Type} | {(row.Required ? "yes" : "no")} | {EscapeCell(row.Description)} |\n");
        return sb.ToString();
    }

    private static string EscapeCell(string s) => s.Replace("|", "\\|");

    private readonly record struct FieldRow(string Path, string Type, bool Required, string Description);

    private static IEnumerable<FieldRow> WalkObject(JsonElement objectSchema, string prefix)
    {
        if (!objectSchema.TryGetProperty("properties", out var props) || props.ValueKind != JsonValueKind.Object)
            yield break;

        var required = RequiredSet(objectSchema);
        foreach (var prop in props.EnumerateObject())
        {
            var path = prefix.Length == 0 ? prop.Name : $"{prefix}.{prop.Name}";
            var description = prop.Value.TryGetProperty("description", out var d) ? d.GetString() ?? "" : "";
            yield return new FieldRow(path, DescribeType(prop.Value), required.Contains(prop.Name), description);

            // Recurse: nested object, or array-of-objects.
            if (IsObjectWithProperties(prop.Value))
            {
                foreach (var r in WalkObject(prop.Value, path)) yield return r;
            }
            else if (prop.Value.TryGetProperty("items", out var items) && IsObjectWithProperties(items))
            {
                foreach (var r in WalkObject(items, $"{path}[]")) yield return r;
            }
        }
    }

    private static string DescribeType(JsonElement schema)
    {
        if (schema.TryGetProperty("const", out var c))
            return $"`{c.GetString()}`";
        if (schema.TryGetProperty("enum", out var en) && en.ValueKind == JsonValueKind.Array)
            return "enum: " + string.Join(" \\| ", en.EnumerateArray().Select(e => $"`{e.GetString()}`"));
        if (!schema.TryGetProperty("type", out var t))
            return "any";

        var type = t.GetString();
        switch (type)
        {
            case "array":
                var itemType = schema.TryGetProperty("items", out var it) ? DescribeType(it) : "any";
                return $"array&lt;{itemType}&gt;";
            case "object":
                if (schema.TryGetProperty("additionalProperties", out var ap) && ap.ValueKind == JsonValueKind.Object)
                    return $"map&lt;string, {DescribeType(ap)}&gt;";
                return "object";
            default:
                return type ?? "any";
        }
    }

    private static bool IsObjectWithProperties(JsonElement schema)
        => schema.TryGetProperty("type", out var t) && t.GetString() == "object"
           && schema.TryGetProperty("properties", out var p) && p.ValueKind == JsonValueKind.Object;

    private static HashSet<string> RequiredSet(JsonElement objectSchema)
    {
        var set = new HashSet<string>(StringComparer.Ordinal);
        if (objectSchema.TryGetProperty("required", out var req) && req.ValueKind == JsonValueKind.Array)
            foreach (var r in req.EnumerateArray()) set.Add(r.GetString()!);
        return set;
    }

    // ── paths ───────────────────────────────────────────────────────────────────

    private static string Normalize(string s) => s.Replace("\r\n", "\n");

    private static string ReadExample(string kind)
    {
        var path = Path.Combine(ContractsDir(), "examples", $"{kind}.example.yaml");
        File.Exists(path).Should().BeTrue($"the {kind} example must exist (ExampleManifestGenerationTests generates it)");
        return Normalize(File.ReadAllText(path));
    }

    private static string DocPath(string kind) => Path.Combine(ContractsDir(), "reference", $"{kind}.md");

    private static string ContractsDir([CallerFilePath] string callerPath = "")
    {
        var testsProjDir = Directory.GetParent(callerPath)!;  // Vais.Agents.Core.Tests
        var agenticDir = testsProjDir.Parent!.Parent!;        // tests -> agentic
        return Path.Combine(agenticDir.FullName, "contracts");
    }
}
