apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pluginName }}
  labels:
    app: {{ .Values.pluginName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.pluginName }}
  ports:
    - port: {{ .Values.pluginPort }}
      targetPort: {{ .Values.pluginPort }}
      protocol: TCP
