// Copyright (c) 2026 VAIS contributors.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using System.ComponentModel;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Vais.Agents.Cli.Commands;

/// <summary>
/// Scaffolds a starter agent-manifest YAML with sensible defaults
/// matching the v0.6 schema. Emits to stdout by default; writes to
/// <c>--output</c> when supplied.
/// </summary>
internal sealed class InitCommand : Command<InitCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [Description("Agent id (used for both the scaffold and the manifest's id field).")]
        [CommandArgument(0, "<name>")]
        public required string Name { get; init; }

        [Description("Output file path. When omitted, the manifest prints to stdout.")]
        [CommandOption("-o|--output")]
        public string? Output { get; init; }

        [Description("Model provider (e.g. openai, anthropic). Defaults to 'openai'.")]
        [CommandOption("--model")]
        public string? ModelProvider { get; init; }

        [Description("Agent execution mode: 'toolCalling' (default) or 'sgr'.")]
        [CommandOption("--mode")]
        public string? AgentMode { get; init; }
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        var yaml = BuildScaffold(settings.Name, settings.ModelProvider, settings.AgentMode);

        if (string.IsNullOrWhiteSpace(settings.Output))
        {
            AnsiConsole.Console.WriteLine(yaml);
        }
        else
        {
            System.IO.File.WriteAllText(settings.Output, yaml);
            AnsiConsole.MarkupLine($"[green]wrote[/] {settings.Output}");
        }
        return ProblemDetailsParser.ExitSuccess;
    }

    /// <summary>Internal for test access — returns the YAML scaffold with defaults applied.</summary>
    internal static string BuildScaffold(string name, string? modelProvider, string? agentMode)
    {
        var provider = string.IsNullOrWhiteSpace(modelProvider) ? "openai" : modelProvider;
        var mode = string.IsNullOrWhiteSpace(agentMode) ? "toolCalling" : agentMode;

        return
$@"# Vais.Agents manifest scaffold — generated by `vais init {name}`.
# Edit the defaults before `vais apply -f` against a real control plane.
id: {name}
version: v1
handler:
  typeName: Vais.Agents.Samples.ChatAgent
  # assemblyName: Vais.Agents.Samples
protocols:
  - kind: Http
tools: []
description: Starter agent for {name}.
labels:
  team: default
model:
  provider: {provider}
  id: <model-id-here>
  # apiKeyRef: env:OPENAI_API_KEY
systemPrompt:
  inline: |
    You are a helpful assistant.
agentMode: {mode}
";
    }
}
